version: "3"
services:
  bridger-hobby-client:
    build: .
    # ports:
    # - 3003:80

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=bridger-shows.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/bridger/data/swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 0.0.0.0:3003:443
    restart: unless-stopped
