name: Update home server containers
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          docker compose pull
          docker compose build
          docker compose up -d