name: Update hobbies
env:
  DUCKDNSTOKEN: ${{ secrets.DUCKDNSTOKEN }}
on: [push, workflow_dispatch]
jobs:
  deploy-application:
    runs-on: [ self-hosted ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: redeploy application
        run: |
          cd client
          docker compose pull
          docker compose build
          docker compose down
          docker compose up -d